Repository openshift/cluster-api-provider-azure, pull requests merged in 2019-09, with the labels that each got.

#76 UPSTREAM: <carry>: openshift: Update machine only when changed
  pkg/cloud/azure/BUILD.bazel
  pkg/cloud/azure/actuators/BUILD.bazel
  pkg/cloud/azure/actuators/machine_scope.go
  pkg/cloud/azure/actuators/machine_scope_test.go
Labels: approved, lgtm, size/L

#80 UPSTREAM: <carry>: openshift: Apply 'make goimports'
  pkg/cloud/azure/services/internalloadbalancers/internalloadbalancers.go
  pkg/cloud/azure/services/networkinterfaces/networkinterfaces.go
  pkg/cloud/azure/services/subnets/subnets.go
Labels: approved, lgtm, size/XS

#78 UPSTREAM: <carry>: openshift: Resync every 20 seconds
  pkg/cloud/azure/actuators/machine/actuator.go
Labels: approved, lgtm, size/XS

#79 UPSTREAM: <carry>: openshift: tag instances with cluster id
  pkg/cloud/azure/actuators/machine/actuator_test.go
  pkg/cloud/azure/actuators/machine/reconciler.go
Labels: approved, lgtm, size/S

#83 Bug 1752088: UPSTREAM: <carry>: openshift: Revendor to bring https://github.com/openshift/cluster-api/pull/72
  Gopkg.lock
  vendor/github.com/openshift/cluster-api/Makefile
  vendor/github.com/openshift/cluster-api/hack/goimports.sh
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M
