Repository openshift/cluster-api-provider-azure, pull requests merged in 2019-06, with the labels that each got.

#36 UPSTREAM: <carry>: openshift: Publish machine conditions during Create and Update operations
  pkg/cloud/azure/actuators/machine/BUILD.bazel
  pkg/cloud/azure/actuators/machine/conditions.go
  pkg/cloud/azure/actuators/machine/conditions_test.go
  pkg/cloud/azure/actuators/machine/reconciler.go
Labels: approved, lgtm, size/L

#38 UPSTREAM: <carry>: openshift: Set internal DNS name
  pkg/cloud/azure/actuators/machine/reconciler.go
Labels: approved, lgtm, size/S

#37 UPSTREAM: <carry>: openshift: Allow to run Create/Delete ops async
  pkg/cloud/azure/actuators/machine/reconciler.go
  pkg/cloud/azure/services/virtualmachines/virtualmachines.go
Labels: approved, lgtm, size/S

#35 UPSTREAM: <carry>: openshift: Set instance subnet and load balancers explicitly
  pkg/apis/azureprovider/v1alpha1/azuremachineproviderconfig_types.go
  pkg/cloud/azure/actuators/machine/actuator_test.go
  pkg/cloud/azure/actuators/machine/reconciler.go
  pkg/cloud/azure/services/networkinterfaces/networkinterfaces.go
Labels: approved, lgtm, size/M

#40 UPSTREAM: <carry>: openshift: Add namespace flag
  cmd/manager/main.go
Labels: approved, lgtm, size/S

#41 UPSTREAM: <carry>: openshift: Allow vnet and managed identity names to be set explicitly
  pkg/apis/azureprovider/v1alpha1/azuremachineproviderconfig_types.go
  pkg/cloud/azure/actuators/machine/reconciler.go
  pkg/cloud/azure/defaults.go
Labels: approved, lgtm, size/M

#43 UPSTREAM: <carry>: openshift: describe how to deploy machine API with azure machine controller over kubernetes
  README.md
  config/bootstrap.sh
  config/controllers/deployment.yaml
  config/generate-bootstrap.sh
Labels: approved, lgtm, size/L

#44 UPSTREAM: <carry>: openshift: Switch builds to use Go 1.12
  Dockerfile
Labels: approved, lgtm, size/XS

#45 UPSTREAM: <carry>: openshift: Expect vnet and managed identity to be always set
  pkg/cloud/azure/actuators/machine/actuator_test.go
  pkg/cloud/azure/actuators/machine/reconciler.go
Labels: approved, lgtm, size/M

#48 UPSTREAM: <carry>: openshift: allowing choosing availability zone for a machine
  pkg/apis/azureprovider/v1alpha1/azuremachineproviderconfig_types.go
  pkg/cloud/azure/actuators/machine/reconciler.go
Labels: approved, lgtm, size/S

#49 UPSTREAM: <carry>: openshift: run 'make generate'
  pkg/apis/azureprovider/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/S
