Repository openshift/cluster-api-provider-azure, pull requests merged in 2019-05, with the labels that each got.

#27 UPSTREAM: <carry>: openshift: remove kubeadm cluser configuration from clusterprovider
  pkg/apis/azureprovider/v1alpha1/BUILD
  pkg/apis/azureprovider/v1alpha1/azureclusterproviderconfig_types.go
  pkg/apis/azureprovider/v1alpha1/azuremachineproviderconfig_types.go
  pkg/apis/azureprovider/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M

#28 UPSTREAM: <carry>: openshift: Update README.md
  README.md
Labels: size/L

#29 UPSTREAM: 202 : openshift: delete OS Disks and Network interface before creating new VM instance, else fails due to previous existence
  pkg/cloud/azure/actuators/machine/BUILD.bazel
  pkg/cloud/azure/actuators/machine/actuator_test.go
  pkg/cloud/azure/actuators/machine/reconciler.go
  pkg/cloud/azure/defaults.go
  pkg/cloud/azure/services/disks/BUILD.bazel
  pkg/cloud/azure/services/disks/disks.go
  pkg/cloud/azure/services/disks/service.go
Labels: approved, lgtm, size/L

#33 UPSTREAM: <carry>: openshift: Set machine addresses
  pkg/cloud/azure/actuators/machine/BUILD.bazel
  pkg/cloud/azure/actuators/machine/reconciler.go
Labels: approved, lgtm, size/M

#34 UPSTREAM: <carry>: openshift: Set machine.Spec.ProviderID
  pkg/cloud/azure/actuators/machine/reconciler.go
  pkg/cloud/azure/defaults.go
Labels: approved, lgtm, size/S
