Repository openshift/cluster-api-provider-azure, pull requests merged in 2019-07, with the labels that each got.

#52 UPSTREAM: <carry>: openshift: Update vendored github.com/openshift/kubernetes-drain
  Gopkg.lock
  vendor/github.com/openshift/kubernetes-drain/drain.go
Labels: approved, lgtm, size/XS

#58 UPSTREAM: <carry>: openshift: Remove dep on bazel binary when running test-e2e target
  Makefile
Labels: approved, lgtm, size/XS

#57 Makefile: add e2e machinations
  Makefile
  hack/e2e.sh
Labels: approved, lgtm, size/S

#60 UPSTREAM: <carry>: openshift: Add omitempty tag so empty strings are omitted from the output
  pkg/apis/azureprovider/v1beta1/azuremachineproviderconfig_types.go
Labels: approved, lgtm, size/S

#61 UPSTREAM: <carry>: openshift: Rename close to persist, make it error aware, stop persisting on exist
  pkg/cloud/azure/actuators/machine/actuator.go
  pkg/cloud/azure/actuators/machine_scope.go
Labels: approved, lgtm, size/M

#62 UPSTREAM: <carry>: openshift: Remove mutating logic from exist and set vm state in update
  pkg/cloud/azure/actuators/machine/reconciler.go
Labels: approved, lgtm, size/L

#59 UPSTREAM: <carry>: openshift: set additional machine annotations/labels with instance bits
  pkg/apis/azureprovider/v1beta1/types.go
  pkg/cloud/azure/actuators/machine/reconciler.go
  pkg/cloud/azure/services/virtualmachines/virtualmachines.go
Labels: approved, lgtm, size/L
