Repository openshift/cluster-api-provider-azure, pull requests merged in 2019-08, with the labels that each got.

#65 UPSTREAM: <carry>: openshift: run 'dep ensure' to bring new deps
  Gopkg.lock
  vendor/github.com/openshift/cluster-api/Gopkg.lock
  vendor/github.com/openshift/cluster-api/Gopkg.toml
  vendor/github.com/openshift/cluster-api/config/crds/machine_v1beta1_machine.yaml
  vendor/github.com/openshift/cluster-api/config/crds/machine_v1beta1_machineset.yaml
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/machine_types.go
  vendor/github.com/openshift/cluster-api/pkg/apis/machine/v1beta1/machineset_types.go
  vendor/github.com/openshift/cluster-api/pkg/controller/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/controller/add_node.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machine/controller.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machinedeployment/BUILD.bazel
  vendor/github.com/openshift/cluster-api/pkg/controller/machinedeployment/controller.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machinedeployment/sync.go
  vendor/github.com/openshift/cluster-api/pkg/controller/machineset/controller.go
Labels: approved, lgtm, size/L

#55 UPSTREAM: <carry>: openshift: Use location from API over secret and unit test
  pkg/cloud/azure/actuators/BUILD.bazel
  pkg/cloud/azure/actuators/machine_scope.go
  pkg/cloud/azure/actuators/machine_scope_test.go
Labels: approved, lgtm, size/L

#66 UPSTREAM: <carry>: openshift: Add support for machine tags
  pkg/apis/azureprovider/v1beta1/azuremachineproviderconfig_types.go
  pkg/apis/azureprovider/v1beta1/zz_generated.deepcopy.go
  pkg/cloud/azure/actuators/machine/reconciler.go
  pkg/cloud/azure/services/virtualmachines/BUILD.bazel
  pkg/cloud/azure/services/virtualmachines/virtualmachines.go
  pkg/cloud/azure/services/virtualmachines/virtualmachines_test.go
Labels: approved, lgtm, size/M

#68 UPSTREAM: <carry>: openshift: create git history verification script
  hack/verify_history.sh
Labels: approved, lgtm, size/M

#63 UPSTREAM: <carry>: openshift: Add unit test for exists()
  pkg/cloud/azure/actuators/machine/BUILD.bazel
  pkg/cloud/azure/actuators/machine/reconciler_test.go
Labels: approved, lgtm, size/M

#70 UPSTREAM: <carry>: openshift: Drop ssh SSHPrivateKey
  cmd/clusterctl/examples/azure/machines.yaml.template
  cmd/clusterctl/examples/azure/machines_no_node.yaml.template
  config/master-machine.yaml
  config/worker-machineset.yaml
  pkg/apis/azureprovider/v1beta1/azuremachineproviderconfig_types.go
  pkg/cloud/azure/actuators/machine/stubs.go
Labels: approved, lgtm, size/S

#73 Check if annotations are initialized before assigning a key
  pkg/cloud/azure/actuators/machine/reconciler.go
Labels: approved, lgtm, size/XS

#72 UPSTREAM: <carry>: openshift: do not randomize public ip name, error instead
  pkg/cloud/azure/actuators/machine/reconciler.go
  pkg/cloud/azure/defaults.go
  pkg/cloud/azure/defaults_test.go
Labels: approved, lgtm, size/M

#75 UPSTREAM: <carry>: openshift: Skip deletion of public IPs with too long names
  pkg/cloud/azure/actuators/machine/reconciler.go
Labels: approved, lgtm, size/XS
