Repository openshift/cluster-api-provider-azure, pull requests merged in 2020-03, with the labels that each got.

#109 Bug 1809001: Remove fqdn from public ip creation
  pkg/cloud/azure/services/publicips/publicips.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#111 Revendor mao with timeout formatting fix
  go.mod
  go.sum
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machinehealthcheck_types.go
  vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go
Labels: approved, lgtm, size/S

#107 Bug 1803844: Support private IPv6 address configurations
  pkg/cloud/azure/services/networkinterfaces/networkinterfaces.go
Labels: approved, bugzilla/valid-bug, lgtm, size/M

#114 Remove bison from OWNERS file
  OWNERS
Labels: approved, lgtm

#115 Restore original make unit behaviour
  Makefile
  hack/ci-test.sh
Labels: approved, lgtm
