Repository openshift/cluster-api-provider-azure, pull requests merged in 2020-09, with the labels that each got.

#159 Bug 1871858: update make generate
  Makefile
  hack/update-generated-deep-copies.sh
  pkg/apis/azureprovider/v1beta1/zz_generated.deepcopy.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#161 Bug 1872080: Add Dockerfile.rhel to match build configuration in ocp-build-data
  Dockerfile.rhel
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#155 Bug 1860229: Fail machine if create request doesn't succeed
  pkg/cloud/azure/actuators/machine/reconciler.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#156 Bug 1864352: Add leader election mechanism to release 4.5
  cmd/manager/main.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#166 Bug 1878163: Updating Dockerfile.rhel baseimages to match ocp-build-data config
  Dockerfile.rhel
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#167 Bug 1878880: re-vendor machine-api-operator at e0db6b65
  go.mod
  go.sum
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machine_webhook.go
  vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#168 BUG 1875598: Ensure the Virtual Machine provider state is set to Unknown when Failed
  go.mod
  go.sum
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machine_webhook.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machineset_webhook.go
  vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#169 Bug 1883497: Fix missing logs due to mixed klog versions
  cmd/manager/main.go
  cmd/termination-handler/main.go
  go.mod
  pkg/cloud/azure/actuators/machine/actuator.go
  pkg/cloud/azure/actuators/machine/actuator_test.go
  pkg/cloud/azure/actuators/machine/conditions.go
  pkg/cloud/azure/actuators/machine/reconciler.go
  pkg/cloud/azure/actuators/machine_scope.go
  pkg/cloud/azure/actuators/machine_scope_test.go
  pkg/cloud/azure/services/applicationsecuritygroups/applicationsecuritygroups.go
  pkg/cloud/azure/services/disks/disks.go
  pkg/cloud/azure/services/groups/groups.go
  pkg/cloud/azure/services/internalloadbalancers/internalloadbalancers.go
  pkg/cloud/azure/services/networkinterfaces/networkinterfaces.go
  pkg/cloud/azure/services/publicips/publicips.go
  pkg/cloud/azure/services/publicloadbalancers/publicloadbalancers.go
  pkg/cloud/azure/services/routetables/routetables.go
  pkg/cloud/azure/services/securitygroups/securitygroups.go
  pkg/cloud/azure/services/subnets/subnets.go
  pkg/cloud/azure/services/virtualmachineextensions/virtualmachineextensions.go
  pkg/cloud/azure/services/virtualmachines/virtualmachines.go
  pkg/cloud/azure/services/virtualnetworks/virtualnetworks.go
  vendor/k8s.io/klog/v2/klogr/README.md
  vendor/k8s.io/klog/v2/klogr/klogr.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
