Repository openshift/cluster-api-provider-azure, pull requests merged in 2020-06, with the labels that each got.

#135 [release-4.4] Bug 1841478: Use ToLower for Subscription ID and Resource Group Name
  pkg/cloud/azure/defaults.go
  pkg/cloud/azure/defaults_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#137 Add dgrigore to approvers
  OWNERS
Labels: approved, lgtm

#139 Add liveness/readiness probes
  cmd/manager/main.go
Labels: approved, lgtm

#138 Expose spot instances to provider spec and reconcile label
  pkg/apis/azureprovider/v1beta1/azuremachineproviderconfig_types.go
  pkg/cloud/azure/actuators/machine/reconciler.go
Labels: approved, lgtm

#129 Fix confusing log in azure
  pkg/cloud/azure/actuators/machine/actuator.go
  pkg/cloud/azure/actuators/machine/reconciler.go
Labels: approved, lgtm

#121 Bug 1821623: UPSTREAM: <carry>: openshift: Update golang/crypto to bring CVE-2020-…
  go.mod
  go.sum
  vendor/golang.org/x/crypto/blowfish/block.go
  vendor/golang.org/x/crypto/blowfish/cipher.go
  vendor/golang.org/x/crypto/blowfish/const.go
  vendor/golang.org/x/crypto/chacha20/chacha_arm64.go
  vendor/golang.org/x/crypto/chacha20/chacha_arm64.s
  vendor/golang.org/x/crypto/chacha20/chacha_generic.go
  vendor/golang.org/x/crypto/chacha20/chacha_noasm.go
  vendor/golang.org/x/crypto/chacha20/chacha_ppc64le.go
  vendor/golang.org/x/crypto/chacha20/chacha_ppc64le.s
  vendor/golang.org/x/crypto/chacha20/chacha_s390x.go
  vendor/golang.org/x/crypto/chacha20/chacha_s390x.s
  vendor/golang.org/x/crypto/chacha20/xor.go
  vendor/golang.org/x/crypto/curve25519/const_amd64.h
  vendor/golang.org/x/crypto/curve25519/const_amd64.s
  vendor/golang.org/x/crypto/curve25519/cswap_amd64.s
  vendor/golang.org/x/crypto/curve25519/curve25519.go
  vendor/golang.org/x/crypto/curve25519/curve25519_amd64.go
  vendor/golang.org/x/crypto/curve25519/curve25519_amd64.s
  vendor/golang.org/x/crypto/curve25519/curve25519_generic.go
  vendor/golang.org/x/crypto/curve25519/curve25519_noasm.go
  vendor/golang.org/x/crypto/curve25519/doc.go
  vendor/golang.org/x/crypto/curve25519/freeze_amd64.s
  vendor/golang.org/x/crypto/curve25519/mul_amd64.s
  vendor/golang.org/x/crypto/curve25519/square_amd64.s
  vendor/golang.org/x/crypto/internal/chacha20/chacha_arm64.go
  vendor/golang.org/x/crypto/internal/chacha20/chacha_generic.go
  vendor/golang.org/x/crypto/internal/chacha20/chacha_ppc64le.go
  vendor/golang.org/x/crypto/internal/chacha20/chacha_s390x.go
  vendor/golang.org/x/crypto/poly1305/bits_compat.go
  vendor/golang.org/x/crypto/poly1305/bits_go1.13.go
  vendor/golang.org/x/crypto/poly1305/poly1305.go
  vendor/golang.org/x/crypto/poly1305/sum_amd64.go
  vendor/golang.org/x/crypto/poly1305/sum_amd64.s
  vendor/golang.org/x/crypto/poly1305/sum_arm.go
  vendor/golang.org/x/crypto/poly1305/sum_arm.s
  vendor/golang.org/x/crypto/poly1305/sum_generic.go
  vendor/golang.org/x/crypto/poly1305/sum_noasm.go
  vendor/golang.org/x/crypto/poly1305/sum_ppc64le.go
  vendor/golang.org/x/crypto/poly1305/sum_ppc64le.s
  vendor/golang.org/x/crypto/poly1305/sum_s390x.go
  vendor/golang.org/x/crypto/ssh/certs.go
  vendor/golang.org/x/crypto/ssh/cipher.go
  vendor/golang.org/x/crypto/ssh/internal/bcrypt_pbkdf/bcrypt_pbkdf.go
  vendor/golang.org/x/crypto/ssh/kex.go
  vendor/golang.org/x/crypto/ssh/keys.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/crypto/ssh/terminal/terminal.go
  vendor/golang.org/x/crypto/ssh/terminal/util_windows.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#127 [release-4.4] Bug 1810531: UPSTREAM: <carry>: openshift: Revendor MAO with timeout formatting fix
  go.mod
  go.sum
  vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm
