Repository openshift/cluster-api-provider-azure, pull requests merged in 2020-11, with the labels that each got.

#180 [OCPCLOUD-809] Add verify-diff check in generate task and enable in CI
  Makefile
  hack/verify-diff.sh
Labels: approved, lgtm

#178 [release-4.6] Bug 1890452: Adding managed disk parameters to support DES encryption
  pkg/apis/azureprovider/v1beta1/types.go
  pkg/apis/azureprovider/v1beta1/zz_generated.deepcopy.go
  pkg/cloud/azure/actuators/machine/stubs.go
  pkg/cloud/azure/services/virtualmachines/virtualmachines.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#185 [OCPCLOUD-977] Bump scripts to Go 1.15
  Dockerfile
  Makefile
  go.mod
  hack/goimports.sh
  vendor/modules.txt
Labels: approved, lgtm

#181 [OCPCLOUD-1043] Bug 1902157: Update termination handler to use node conditions
  pkg/termination/termination.go
  pkg/termination/termination_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
