Repository openshift/cluster-api-provider-azure, pull requests merged in 2020-07, with the labels that each got.

#122 OCPCLOUD-492: Run all machine api Controllers using leader election
  cmd/manager/main.go
Labels: approved, lgtm, release/4.6

#140 Bug 1845610: Windows VM MachineSet error on Azure
  pkg/cloud/azure/services/virtualmachines/virtualmachines.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#150 Ensure empty max price does not cause error when creating a spot VM
  pkg/cloud/azure/actuators/machine/reconciler.go
  pkg/cloud/azure/actuators/machine/reconciler_test.go
Labels: approved, lgtm

#153 Bug 1857175: Revendor mao to bring https://github.com/openshift/machine-api-operator/pull/644
  go.mod
  go.sum
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machine_types.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machine_webhook.go
  vendor/github.com/openshift/machine-api-operator/pkg/apis/machine/v1beta1/machineset_webhook.go
  vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#152 BUG 1858400: [Performance] Lease refresh period for machine-api-controllers is too high, causes heavy writes to etcd at idle
  cmd/manager/main.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#151 Extend testing of setMachineCloudProviderSpecifics
  pkg/cloud/azure/actuators/machine/reconciler.go
  pkg/cloud/azure/actuators/machine/reconciler_test.go
Labels: approved, lgtm
