Repository openshift/cluster-api-provider-azure, pull requests merged in 2020-05, with the labels that each got.

#128 [release-4.5] Bug 1831609: Refactor azure actuator: Removed deprecated v1apha1 api
  config/master-machine.yaml
  config/worker-machineset.yaml
  pkg/apis/addtoscheme_azureprovider_v1alpha1.go
  pkg/apis/azureprovider/v1alpha1/azureclusterproviderconfig_types.go
  pkg/apis/azureprovider/v1alpha1/azureclusterproviderstatus_types.go
  pkg/apis/azureprovider/v1alpha1/doc.go
  pkg/apis/azureprovider/v1alpha1/register.go
  pkg/apis/azureprovider/v1alpha1/types.go
  pkg/apis/azureprovider/v1alpha1/zz_generated.deepcopy.go
  pkg/cloud/azure/actuators/getters.go
  pkg/cloud/azure/actuators/machine/actuator_test.go
  pkg/cloud/azure/actuators/machine/reconciler.go
  pkg/cloud/azure/actuators/machine_scope.go
  pkg/cloud/azure/actuators/machine_scope_test.go
  pkg/cloud/azure/actuators/scope.go
  pkg/cloud/azure/services/applicationsecuritygroups/applicationsecuritygroups.go
  pkg/cloud/azure/services/applicationsecuritygroups/service.go
  pkg/cloud/azure/services/availabilityzones/availabilityzones.go
  pkg/cloud/azure/services/availabilityzones/service.go
  pkg/cloud/azure/services/disks/disks.go
  pkg/cloud/azure/services/disks/service.go
  pkg/cloud/azure/services/groups/groups.go
  pkg/cloud/azure/services/groups/service.go
  pkg/cloud/azure/services/internalloadbalancers/internalloadbalancers.go
  pkg/cloud/azure/services/internalloadbalancers/service.go
  pkg/cloud/azure/services/mock_interfaces.go
  pkg/cloud/azure/services/mock_interfaces_helper.go
  pkg/cloud/azure/services/networkinterfaces/networkinterfaces.go
  pkg/cloud/azure/services/networkinterfaces/service.go
  pkg/cloud/azure/services/publicips/publicips.go
  pkg/cloud/azure/services/publicips/service.go
  pkg/cloud/azure/services/publicloadbalancers/publicloadbalancers.go
  pkg/cloud/azure/services/publicloadbalancers/service.go
  pkg/cloud/azure/services/routetables/routetables.go
  pkg/cloud/azure/services/routetables/service.go
  pkg/cloud/azure/services/securitygroups/securitygroups.go
  pkg/cloud/azure/services/securitygroups/service.go
  pkg/cloud/azure/services/subnets/service.go
  pkg/cloud/azure/services/subnets/subnets.go
  pkg/cloud/azure/services/virtualmachineextensions/service.go
  pkg/cloud/azure/services/virtualmachineextensions/virtualmachineextensions.go
  pkg/cloud/azure/services/virtualmachines/service.go
  pkg/cloud/azure/services/virtualmachines/virtualmachines.go
  pkg/cloud/azure/services/virtualnetworks/service.go
  pkg/cloud/azure/services/virtualnetworks/virtualnetworks.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#118 Bug 1832186: Bump all dependencies to kube 1.18
  go.mod
  go.sum
  vendor/k8s.io/utils/exec/README.md
  vendor/k8s.io/utils/pointer/README.md
  vendor/modules.txt
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#130 Bug 1808971: Machine status shows "running" when an instance was terminated
  go.mod
  go.sum
  vendor/github.com/openshift/machine-api-operator/pkg/controller/machine/controller.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#134 Bug 1837341: Use ToLower for Subscription ID and Resource Group Name
  pkg/cloud/azure/defaults.go
  pkg/cloud/azure/defaults_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm
