Repository openshift/cluster-api-provider-azure, pull requests merged in 2021-02, with the labels that each got.

#183 BUG 1900454: Add SecurityProfile.EncryptionAtHost parameter to enable host-based VM encryption
  pkg/apis/azureprovider/v1beta1/azuremachineproviderconfig_types.go
  pkg/apis/azureprovider/v1beta1/types.go
  pkg/apis/azureprovider/v1beta1/zz_generated.deepcopy.go
  pkg/cloud/azure/actuators/machine/reconciler.go
  pkg/cloud/azure/services/virtualmachines/virtualmachines.go
  pkg/cloud/azure/services/virtualmachines/virtualmachines_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#195 Updating ose-azure-machine-controllers builder & base images to be consistent with ART
  Dockerfile.rhel
Labels: approved, lgtm

#199 "Bug 1912531: revendor mao"
  go.mod
  go.sum
  vendor/k8s.io/api/apps/v1beta1/types.go
  vendor/k8s.io/api/apps/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/api/apps/v1beta2/types.go
  vendor/k8s.io/api/apps/v1beta2/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/api/extensions/v1beta1/types.go
  vendor/k8s.io/api/extensions/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/reflector.go
  vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/endpointslock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go
  vendor/k8s.io/client-go/transport/cache.go
  vendor/k8s.io/kubectl/pkg/drain/drain.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm
